import { useState } from "react";

import {
    LONG_TEXT,
    MAX_ROWS,
    MIN_ROWS,
    REVIEW_LIMIT,
} from "@thewaver/ss-playground-core/App/Pages/TextAreaPage/TextAreaPage.const";

import { PageExamples } from "../../PageComponents/Examples/Examples";
import { AutoSizingExample } from "./Examples/AutoSizing";
import { AutoSizingCappedExample } from "./Examples/AutoSizingCapped";
import { DisabledExample } from "./Examples/Disabled";
import { ErroredExample } from "./Examples/Errored";
import { FixedHeightExample } from "./Examples/FixedHeight";
import { LabeledExample } from "./Examples/Labeled";
import { ReachableExample } from "./Examples/Reachable";
import { ReadOnlyExample } from "./Examples/ReadOnly";

const EXAMPLES_ROOT = "/src/App/Pages/TextAreaPage/Examples";

export const TextAreaPage = () => {
    const fixedState = useState("");
    const growingState = useState("");
    const cappedState = useState(LONG_TEXT);
    const readOnlyState = useState("Generated by the server,\nacross two lines.");
    const disabledState = useState("Cannot be edited");
    const reachableState = useState("Cannot be edited either");
    const erroredState = useState("Too short");
    const labeledState = useState("");

    const examples = [
        {
            key: "fixedHeight",
            name: "Fixed height",
            readout: () => `length: ${fixedState[0].length} — the painter sizes the box and it stays put`,
            component: () => <FixedHeightExample valueState={fixedState} />,
            path: `${EXAMPLES_ROOT}/FixedHeight.tsx`,
        },
        {
            key: "autoSizing",
            name: "Auto-sizing",
            readout: () =>
                `length: ${growingState[0].length} — grows from ${MIN_ROWS} rows with no ceiling, so it never scrolls`,
            component: () => <AutoSizingExample valueState={growingState} />,
            path: `${EXAMPLES_ROOT}/AutoSizing.tsx`,
        },
        {
            key: "autoSizingCapped",
            name: "Auto-sizing, capped",
            readout: () => `length: ${cappedState[0].length} — stops growing at ${MAX_ROWS} rows and scrolls`,
            component: () => <AutoSizingCappedExample valueState={cappedState} />,
            path: `${EXAMPLES_ROOT}/AutoSizingCapped.tsx`,
        },
        {
            key: "readOnly",
            name: "Read-only",
            readout: () => `length: ${readOnlyState[0].length} — selectable and copyable, never editable`,
            component: () => <ReadOnlyExample valueState={readOnlyState} />,
            path: `${EXAMPLES_ROOT}/ReadOnly.tsx`,
        },
        {
            key: "disabled",
            name: "Disabled",
            readout: () => `length: ${disabledState[0].length}`,
            component: () => <DisabledExample valueState={disabledState} />,
            path: `${EXAMPLES_ROOT}/Disabled.tsx`,
        },
        {
            key: "reachable",
            name: "Disabled + reachable",
            readout: () => `length: ${reachableState[0].length}`,
            component: () => <ReachableExample valueState={reachableState} />,
            path: `${EXAMPLES_ROOT}/Reachable.tsx`,
        },
        {
            key: "errored",
            name: "Error",
            readout: () => `length: ${erroredState[0].length} — fewer than ${REVIEW_LIMIT} characters is an error`,
            component: () => <ErroredExample valueState={erroredState} />,
            path: `${EXAMPLES_ROOT}/Errored.tsx`,
        },
        {
            key: "label",
            name: "In a Label",
            readout: () => `length: ${labeledState[0].length}`,
            component: () => <LabeledExample valueState={labeledState} />,
            path: `${EXAMPLES_ROOT}/Labeled.tsx`,
        },
    ];

    return <PageExamples items={examples} minColumnWidth={400} />;
};
