import { createMemo, createSignal } from "solid-js";

import { PageExamples } from "../../PageComponents/Examples/Examples";
import { BothAdornmentsExample } from "./Examples/BothAdornments";
import { DefaultExample } from "./Examples/Default";
import { DisabledExample } from "./Examples/Disabled";
import { ErroredExample } from "./Examples/Errored";
import { LabelledExample } from "./Examples/Labelled";
import { NumberFieldExample } from "./Examples/NumberField";
import { PasswordExample } from "./Examples/Password";
import { ReachableExample } from "./Examples/Reachable";
import { ReadOnlyExample } from "./Examples/ReadOnly";
import { RefusingSetterExample } from "./Examples/RefusingSetter";
import { TransformingSetterExample } from "./Examples/TransformingSetter";
import { PIN_LENGTH, QUANTITY_STEP } from "./TextInputPage.const";

const EXAMPLES_ROOT = "/src/App/Pages/TextInputPage/Examples";

export const TextInputPage = () => {
    const defaultSignal = createSignal("");
    const passwordSignal = createSignal("");
    const readOnlySignal = createSignal("Generated by the server");
    const disabledSignal = createSignal("Cannot be edited");
    const reachableSignal = createSignal("Cannot be edited either");
    const erroredSignal = createSignal("not-an-email");
    const labelledSignal = createSignal("");
    const codeSignal = createSignal("");
    const pinSignal = createSignal("");
    const amountSignal = createSignal("");
    const quantitySignal = createSignal("10");
    const revealSignal = createSignal(false);

    const getExamples = createMemo(() => [
        {
            key: "default",
            name: "Default",
            readout: () => `value: "${defaultSignal[0]()}"`,
            component: () => <DefaultExample valueSignal={defaultSignal} />,
            path: `${EXAMPLES_ROOT}/Default.tsx`,
        },
        {
            key: "transformingSetter",
            name: "Transforming setter",
            readout: () => `value: "${codeSignal[0]()}" — type lowercase mid-string, the caret must not jump`,
            component: () => <TransformingSetterExample valueSignal={codeSignal} />,
            path: `${EXAMPLES_ROOT}/TransformingSetter.tsx`,
        },
        {
            key: "refusingSetter",
            name: "Refusing setter",
            readout: () => `value: "${pinSignal[0]()}" — letters are refused, ${PIN_LENGTH} digits max`,
            component: () => <RefusingSetterExample valueSignal={pinSignal} />,
            path: `${EXAMPLES_ROOT}/RefusingSetter.tsx`,
        },
        {
            key: "password",
            name: "Password",
            readout: () => `value: "${passwordSignal[0]()}" | revealed: ${revealSignal[0]()}`,
            component: () => <PasswordExample valueSignal={passwordSignal} revealSignal={revealSignal} />,
            path: `${EXAMPLES_ROOT}/Password.tsx`,
        },
        {
            key: "bothAdornments",
            name: "Both adornments",
            readout: () => `value: "${amountSignal[0]()}"`,
            component: () => <BothAdornmentsExample valueSignal={amountSignal} />,
            path: `${EXAMPLES_ROOT}/BothAdornments.tsx`,
        },
        {
            key: "number",
            name: "Number",
            readout: () => `value: "${quantitySignal[0]()}" — arrows step by ${QUANTITY_STEP}, no spinner buttons`,
            component: () => <NumberFieldExample valueSignal={quantitySignal} />,
            path: `${EXAMPLES_ROOT}/NumberField.tsx`,
        },
        {
            key: "readOnly",
            name: "Read-only",
            readout: () => `value: "${readOnlySignal[0]()}" — selectable and copyable, never editable`,
            component: () => <ReadOnlyExample valueSignal={readOnlySignal} />,
            path: `${EXAMPLES_ROOT}/ReadOnly.tsx`,
        },
        {
            key: "disabled",
            name: "Disabled",
            readout: () => `value: "${disabledSignal[0]()}"`,
            component: () => <DisabledExample valueSignal={disabledSignal} />,
            path: `${EXAMPLES_ROOT}/Disabled.tsx`,
        },
        {
            key: "reachable",
            name: "Disabled + reachable",
            readout: () => `value: "${reachableSignal[0]()}"`,
            component: () => <ReachableExample valueSignal={reachableSignal} />,
            path: `${EXAMPLES_ROOT}/Reachable.tsx`,
        },
        {
            key: "errored",
            name: "Error",
            readout: () => `value: "${erroredSignal[0]()}"`,
            component: () => <ErroredExample valueSignal={erroredSignal} />,
            path: `${EXAMPLES_ROOT}/Errored.tsx`,
        },
        {
            key: "label",
            name: "In a Label",
            readout: () => `value: "${labelledSignal[0]()}"`,
            component: () => <LabelledExample valueSignal={labelledSignal} />,
            path: `${EXAMPLES_ROOT}/Labelled.tsx`,
        },
    ]);

    return <PageExamples items={getExamples} />;
};
