import { createMemo, createSignal } from "solid-js";

import { PageExamples } from "../../PageComponents/Examples/Examples";
import { BothAdornmentsExample } from "./Examples/BothAdornments";
import { CitiesExample } from "./Examples/Cities";
import { DefaultExample } from "./Examples/Default";
import { DisabledExample } from "./Examples/Disabled";
import { EditableExample } from "./Examples/Editable";
import { ErroredExample } from "./Examples/Errored";
import { LabeledExample } from "./Examples/Labeled";
import { NumberFieldExample } from "./Examples/NumberField";
import { OneTimeCodeExample } from "./Examples/OneTimeCode";
import { PasswordExample } from "./Examples/Password";
import { ReachableExample } from "./Examples/Reachable";
import { ReadOnlyExample } from "./Examples/ReadOnly";
import { RefusingSetterExample } from "./Examples/RefusingSetter";
import { TransformingSetterExample } from "./Examples/TransformingSetter";
import { CITIES, PIN_LENGTH, QUANTITY_STEP } from "./TextInputPage.const";

const EXAMPLES_ROOT = "/src/App/Pages/TextInputPage/Examples";

export const TextInputPage = () => {
    const defaultSignal = createSignal("");
    const passwordSignal = createSignal("");
    const readOnlySignal = createSignal("Generated by the server");
    const disabledSignal = createSignal("Cannot be edited");
    const reachableSignal = createSignal("Cannot be edited either");
    const erroredSignal = createSignal("not-an-email");
    const labeledSignal = createSignal("");
    const codeSignal = createSignal("");
    const pinSignal = createSignal("");
    const amountSignal = createSignal("");
    const quantitySignal = createSignal("10");
    const revealSignal = createSignal(false);
    const citySignal = createSignal("");
    const oneTimeCodeSignal = createSignal("");
    const editableSignal = createSignal("Ada Lovelace");
    const editingSignal = createSignal(false);

    const getCitySuggestions = createMemo(() => {
        const query = citySignal[0]().trim().toLocaleLowerCase();

        if (!query) return [];

        return CITIES.filter((city) => city.name.toLocaleLowerCase().startsWith(query));
    });

    const getExamples = createMemo(() => [
        {
            key: "default",
            name: "Default",
            readout: () => `value: "${defaultSignal[0]()}"`,
            component: () => <DefaultExample valueSignal={defaultSignal} />,
            path: `${EXAMPLES_ROOT}/Default.tsx`,
        },
        {
            key: "transformingSetter",
            name: "Transforming setter",
            readout: () => `value: "${codeSignal[0]()}" — type lowercase mid-string, the caret must not jump`,
            component: () => <TransformingSetterExample valueSignal={codeSignal} />,
            path: `${EXAMPLES_ROOT}/TransformingSetter.tsx`,
        },
        {
            key: "refusingSetter",
            name: "Refusing setter",
            readout: () => `value: "${pinSignal[0]()}" — letters are refused, ${PIN_LENGTH} digits max`,
            component: () => <RefusingSetterExample valueSignal={pinSignal} />,
            path: `${EXAMPLES_ROOT}/RefusingSetter.tsx`,
        },
        {
            key: "suggestions",
            name: "Suggestions",
            readout: () =>
                `value: "${citySignal[0]()}" — ${getCitySuggestions().length} suggested; any text is kept, and Enter only picks once the arrows have moved into the list`,
            component: () => <CitiesExample valueSignal={citySignal} suggestions={getCitySuggestions} />,
            path: `${EXAMPLES_ROOT}/Cities.tsx`,
        },
        {
            key: "oneTimeCode",
            name: "One-time code",
            readout: () =>
                `value: "${oneTimeCodeSignal[0]()}" — one field painted as ${PIN_LENGTH} cells, the next empty one marked while focused`,
            component: () => <OneTimeCodeExample valueSignal={oneTimeCodeSignal} />,
            path: `${EXAMPLES_ROOT}/OneTimeCode.tsx`,
        },
        {
            key: "editable",
            name: "Edit in place",
            readout: () =>
                `value: "${editableSignal[0]()}" | editing: ${editingSignal[0]()} — Enter or leaving keeps the edit, Escape puts the old text back`,
            component: () => <EditableExample valueSignal={editableSignal} editingSignal={editingSignal} />,
            path: `${EXAMPLES_ROOT}/Editable.tsx`,
        },
        {
            key: "password",
            name: "Password",
            readout: () => `value: "${passwordSignal[0]()}" | revealed: ${revealSignal[0]()}`,
            component: () => <PasswordExample valueSignal={passwordSignal} revealSignal={revealSignal} />,
            path: `${EXAMPLES_ROOT}/Password.tsx`,
        },
        {
            key: "bothAdornments",
            name: "Both adornments",
            readout: () => `value: "${amountSignal[0]()}"`,
            component: () => <BothAdornmentsExample valueSignal={amountSignal} />,
            path: `${EXAMPLES_ROOT}/BothAdornments.tsx`,
        },
        {
            key: "number",
            name: "Number",
            readout: () => `value: "${quantitySignal[0]()}" — arrows step by ${QUANTITY_STEP}, no spinner buttons`,
            component: () => <NumberFieldExample valueSignal={quantitySignal} />,
            path: `${EXAMPLES_ROOT}/NumberField.tsx`,
        },
        {
            key: "readOnly",
            name: "Read-only",
            readout: () => `value: "${readOnlySignal[0]()}" — selectable and copyable, never editable`,
            component: () => <ReadOnlyExample valueSignal={readOnlySignal} />,
            path: `${EXAMPLES_ROOT}/ReadOnly.tsx`,
        },
        {
            key: "disabled",
            name: "Disabled",
            readout: () => `value: "${disabledSignal[0]()}"`,
            component: () => <DisabledExample valueSignal={disabledSignal} />,
            path: `${EXAMPLES_ROOT}/Disabled.tsx`,
        },
        {
            key: "reachable",
            name: "Disabled + reachable",
            readout: () => `value: "${reachableSignal[0]()}"`,
            component: () => <ReachableExample valueSignal={reachableSignal} />,
            path: `${EXAMPLES_ROOT}/Reachable.tsx`,
        },
        {
            key: "errored",
            name: "Error",
            readout: () => `value: "${erroredSignal[0]()}"`,
            component: () => <ErroredExample valueSignal={erroredSignal} />,
            path: `${EXAMPLES_ROOT}/Errored.tsx`,
        },
        {
            key: "label",
            name: "In a Label",
            readout: () => `value: "${labeledSignal[0]()}"`,
            component: () => <LabeledExample valueSignal={labeledSignal} />,
            path: `${EXAMPLES_ROOT}/Labeled.tsx`,
        },
    ]);

    return <PageExamples items={getExamples} />;
};
