<script setup lang="ts">
import { computed, shallowRef } from "vue";

import { CITIES, PIN_LENGTH, QUANTITY_STEP } from "@thewaver/ss-playground/App/Pages/TextInputPage/TextInputPage.const";

import type { ExampleDefs } from "../../PageComponents/Examples/Examples.types";
import PageExamples from "../../PageComponents/Examples/PageExamples.vue";
import BothAdornmentsExample from "./Examples/BothAdornments.vue";
import CitiesExample from "./Examples/Cities.vue";
import DefaultExample from "./Examples/Default.vue";
import DisabledExample from "./Examples/Disabled.vue";
import EditableExample from "./Examples/Editable.vue";
import ErroredExample from "./Examples/Errored.vue";
import LabeledExample from "./Examples/Labeled.vue";
import NumberFieldExample from "./Examples/NumberField.vue";
import PasswordExample from "./Examples/Password.vue";
import ReachableExample from "./Examples/Reachable.vue";
import ReadOnlyExample from "./Examples/ReadOnly.vue";
import RefusingSetterExample from "./Examples/RefusingSetter.vue";
import TransformingSetterExample from "./Examples/TransformingSetter.vue";

const EXAMPLES_ROOT = "/src/App/Pages/TextInputPage/Examples";

const defaultValue = shallowRef("");
const passwordValue = shallowRef("");
const readOnlyValue = shallowRef("Generated by the server");
const disabledValue = shallowRef("Cannot be edited");
const reachableValue = shallowRef("Cannot be edited either");
const erroredValue = shallowRef("not-an-email");
const labeledValue = shallowRef("");
const codeValue = shallowRef("");
const pinValue = shallowRef("");
const amountValue = shallowRef("");
const quantityValue = shallowRef("10");
const isRevealed = shallowRef(false);
const cityValue = shallowRef("");
const editableValue = shallowRef("Ada Lovelace");
const isEditing = shallowRef(false);

const citySuggestions = computed(() => {
    const query = cityValue.value.trim().toLocaleLowerCase();

    if (!query) return [];

    return CITIES.filter((city) => city.name.toLocaleLowerCase().startsWith(query));
});

const examples: ExampleDefs[] = [
    {
        key: "default",
        name: "Default",
        readout: () => `value: "${defaultValue.value}"`,
        path: `${EXAMPLES_ROOT}/Default.vue`,
    },
    {
        key: "transformingSetter",
        name: "Transforming setter",
        readout: () => `value: "${codeValue.value}" — type lowercase mid-string, the caret must not jump`,
        path: `${EXAMPLES_ROOT}/TransformingSetter.vue`,
    },
    {
        key: "refusingSetter",
        name: "Refusing setter",
        readout: () => `value: "${pinValue.value}" — letters are refused, ${PIN_LENGTH} digits max`,
        path: `${EXAMPLES_ROOT}/RefusingSetter.vue`,
    },
    {
        key: "suggestions",
        name: "Suggestions",
        readout: () =>
            `value: "${cityValue.value}" — ${citySuggestions.value.length} suggested; any text is kept, and Enter only picks once the arrows have moved into the list`,
        path: `${EXAMPLES_ROOT}/Cities.vue`,
    },
    {
        key: "editable",
        name: "Edit in place",
        readout: () =>
            `value: "${editableValue.value}" | editing: ${isEditing.value} — Enter or leaving keeps the edit, Escape puts the old text back`,
        path: `${EXAMPLES_ROOT}/Editable.vue`,
    },
    {
        key: "password",
        name: "Password",
        readout: () => `value: "${passwordValue.value}" | revealed: ${isRevealed.value}`,
        path: `${EXAMPLES_ROOT}/Password.vue`,
    },
    {
        key: "bothAdornments",
        name: "Both adornments",
        readout: () => `value: "${amountValue.value}"`,
        path: `${EXAMPLES_ROOT}/BothAdornments.vue`,
    },
    {
        key: "number",
        name: "Number",
        readout: () => `value: "${quantityValue.value}" — arrows step by ${QUANTITY_STEP}, no spinner buttons`,
        path: `${EXAMPLES_ROOT}/NumberField.vue`,
    },
    {
        key: "readOnly",
        name: "Read-only",
        readout: () => `value: "${readOnlyValue.value}" — selectable and copyable, never editable`,
        path: `${EXAMPLES_ROOT}/ReadOnly.vue`,
    },
    {
        key: "disabled",
        name: "Disabled",
        readout: () => `value: "${disabledValue.value}"`,
        path: `${EXAMPLES_ROOT}/Disabled.vue`,
    },
    {
        key: "reachable",
        name: "Disabled + reachable",
        readout: () => `value: "${reachableValue.value}"`,
        path: `${EXAMPLES_ROOT}/Reachable.vue`,
    },
    {
        key: "errored",
        name: "Error",
        readout: () => `value: "${erroredValue.value}"`,
        path: `${EXAMPLES_ROOT}/Errored.vue`,
    },
    {
        key: "label",
        name: "In a Label",
        readout: () => `value: "${labeledValue.value}"`,
        path: `${EXAMPLES_ROOT}/Labeled.vue`,
    },
];
</script>

<template>
    <PageExamples :items="examples">
        <template #default>
            <DefaultExample v-model:value="defaultValue" />
        </template>

        <template #transformingSetter>
            <TransformingSetterExample v-model:value="codeValue" />
        </template>

        <template #refusingSetter>
            <RefusingSetterExample v-model:value="pinValue" />
        </template>

        <template #suggestions>
            <CitiesExample v-model:value="cityValue" :suggestions="citySuggestions" />
        </template>

        <template #editable>
            <EditableExample v-model:value="editableValue" v-model:editing="isEditing" />
        </template>

        <template #password>
            <PasswordExample v-model:value="passwordValue" v-model:reveal="isRevealed" />
        </template>

        <template #bothAdornments>
            <BothAdornmentsExample v-model:value="amountValue" />
        </template>

        <template #number>
            <NumberFieldExample v-model:value="quantityValue" />
        </template>

        <template #readOnly>
            <ReadOnlyExample v-model:value="readOnlyValue" />
        </template>

        <template #disabled>
            <DisabledExample v-model:value="disabledValue" />
        </template>

        <template #reachable>
            <ReachableExample v-model:value="reachableValue" />
        </template>

        <template #errored>
            <ErroredExample v-model:value="erroredValue" />
        </template>

        <template #label>
            <LabeledExample v-model:value="labeledValue" />
        </template>
    </PageExamples>
</template>
