import type { TreemapNode } from "@thewaver/ss-components";

const leaf = (value: string, weight: number): TreemapNode<string> => ({ value, weight });

const branch = (value: string, ...children: TreemapNode<string>[]): TreemapNode<string> => ({ value, children });

export const formatLines = (lines: number) => `${lines.toLocaleString("en-US")} lines`;

export const LIBRARY: TreemapNode<string> = branch(
    "src",
    branch(
        "Abstracts",
        leaf("Anchor", 598),
        leaf("Carrier", 680),
        leaf("CheckedState", 23),
        leaf("ColorExtractor", 151),
        leaf("Cutout", 65),
        leaf("DateTimeValue", 112),
        leaf("DateValue", 566),
        leaf("Dismisser", 182),
        leaf("ElementFader", 241),
        leaf("ElementObserver", 752),
        leaf("Elevation", 124),
        leaf("Flattener", 122),
        leaf("FocusManager", 268),
        leaf("FrameRateMonitor", 119),
        leaf("Glass", 308),
        leaf("HoverIntent", 408),
        leaf("InteractionTracker", 1189),
        leaf("LiveAnnouncer", 96),
        leaf("MaskedField", 206),
        leaf("MediaQueryMonitor", 164),
        leaf("Navigator", 320),
        leaf("Placement", 756),
        leaf("PointerTracker", 254),
        leaf("Proximity", 330),
        leaf("Rotator", 505),
        leaf("Selection", 264),
        leaf("SignalMirror", 283),
        leaf("Smoother", 140),
        leaf("TextSync", 471),
        leaf("Typeahead", 198),
        leaf("Viewport", 131),
        leaf("Virtualizer", 226),
    ),
    branch("Composites", leaf("GlassSurface", 149), leaf("Surface", 252)),
    branch(
        "Essentials",
        branch("Accordions", leaf("Accordion", 292), leaf("Collapsible", 389)),
        leaf("AudioSwitcher", 281),
        leaf("Breadcrumbs", 195),
        leaf("Button", 191),
        branch("Carousels", leaf("DrumCarousel", 4), leaf("TrackCarousel", 4)),
        leaf("Drawer", 20),
        leaf("EdgeFader", 291),
        leaf("Form", 148),
        leaf("HoverCard", 394),
        leaf("ImageSwitcher", 177),
        branch(
            "Input",
            leaf("Calendar", 925),
            leaf("Checkbox", 51),
            leaf("CheckboxGroup", 211),
            leaf("Clock", 717),
            leaf("ColorArea", 362),
            leaf("ColorInput", 421),
            leaf("CurrencyInput", 207),
            leaf("DateInput", 352),
            leaf("DatePicker", 181),
            leaf("DateRangePicker", 253),
            leaf("DateTimePicker", 174),
            leaf("FileInput", 570),
            leaf("FormField", 199),
            leaf("FormSection", 117),
            leaf("Label", 141),
            leaf("Listbox", 1201),
            leaf("MultiListbox", 42),
            leaf("MultiSelect", 57),
            leaf("NumberInput", 564),
            leaf("Radio", 71),
            leaf("RadioGroup", 500),
            leaf("Range", 791),
            leaf("RangeCalendar", 116),
            leaf("SegmentedInput", 358),
            leaf("Select", 673),
            leaf("TagInput", 423),
            leaf("TextArea", 16),
            leaf("TextInput", 184),
            leaf("TimeInput", 373),
            leaf("TimePicker", 179),
            leaf("Toggle", 21),
        ),
        leaf("Menubar", 7),
        branch("Menus", leaf("FanMenu", 56), leaf("Menu", 1851), leaf("WheelMenu", 263)),
        leaf("Modal", 426),
        leaf("Paginator", 502),
        leaf("Preview", 279),
        leaf("Progress", 209),
        leaf("Scroller", 380),
        leaf("Sidebar", 301),
        leaf("SlideButton", 507),
        leaf("Sortable", 1259),
        leaf("SplitPane", 605),
        branch("Spotlights", leaf("SpotlightGuide", 4), leaf("SpotlightHint", 4), leaf("SpotlightPrompt", 4)),
        leaf("Stepper", 350),
        leaf("Table", 1500),
        leaf("TableOfContents", 341),
        leaf("Tabs", 578),
        leaf("Toasts", 736),
        leaf("Toolbar", 787),
        leaf("Tooltip", 227),
        leaf("Tree", 764),
        leaf("ViewportWrapper", 230),
    ),
    branch(
        "Exotics",
        leaf("Bracket", 756),
        leaf("CardStack", 674),
        leaf("CellAnimation", 646),
        leaf("CirclePacking", 909),
        leaf("Corners", 160),
        leaf("Cuboid", 1019),
        leaf("Die", 881),
        leaf("FlipCard", 261),
        leaf("Formation", 93),
        leaf("Icicle", 584),
        branch("Mosaics", leaf("ElementMosaic", 65), leaf("ImageMosaic", 191)),
        leaf("Odometer", 739),
        leaf("ParticleField", 586),
        leaf("ParticleSpawner", 601),
        leaf("PatchBoard", 1887),
        branch(
            "PointerEffects",
            leaf("LightCatcher", 136),
            leaf("ShadowCaster", 147),
            leaf("Tilter", 179),
            leaf("PointerEffects files", 236),
        ),
        branch("Reveals", leaf("Reveal", 337), leaf("ScratchCard", 654)),
        leaf("RichText", 335),
        leaf("Satellite", 208),
        leaf("ScanlineAnimation", 57),
        leaf("ScrambleText", 512),
        leaf("Shape", 276),
        leaf("SortableGrid", 1858),
        leaf("Staircase", 147),
        leaf("Sunburst", 563),
        leaf("TileBoard", 1277),
        leaf("Timeline", 1784),
        leaf("Trail", 435),
        leaf("Treemap", 867),
        leaf("Typewriter", 656),
        branch("Wheels", leaf("DrumWheel", 4), leaf("OverheadWheel", 4)),
    ),
    branch(
        "Generators",
        leaf("CellAnimationBreakpoints", 141),
        leaf("CellAnimationKeyframes", 231),
        leaf("CellAnimationPlayback", 80),
        leaf("CellAnimationWeights", 616),
        leaf("CellAnimationZones", 129),
        leaf("PlacementLayouts", 732),
        leaf("ProximityEffects", 230),
        branch(
            "SVGDefs",
            leaf("SVGAnimations", 223),
            leaf("SVGFilters", 899),
            leaf("SVGGradients", 282),
            leaf("SVGPatterns", 83),
            leaf("SVGDefs files", 24),
        ),
    ),
    branch(
        "Primitives",
        leaf("Barrel", 313),
        leaf("BinarySwitch", 229),
        leaf("Carousel", 825),
        leaf("InteractionWrapper", 231),
        leaf("Mosaic", 1154),
        leaf("PlacementBox", 240),
        leaf("PlacementItem", 239),
        leaf("Popover", 289),
        leaf("PopupTrigger", 77),
        leaf("Spotlight", 423),
        leaf("TextField", 702),
        leaf("Wheel", 562),
    ),
    branch(
        "Samples",
        branch("Bracket", leaf("Connectors", 207)),
        branch(
            "CellAnimation",
            branch("Keyframes", leaf("Samples", 1286), leaf("Keyframes files", 378)),
            leaf("Origins", 31),
            branch("Weights", leaf("Samples", 917), leaf("Weights files", 252)),
        ),
        branch("Die", leaf("Shapes", 81)),
        branch("Odometer", leaf("Reels", 78)),
        branch("PatchBoard", leaf("Snaps", 12)),
        branch("Placement", leaf("Layouts", 18)),
        branch("Proximity", leaf("Effects", 13)),
        branch(
            "SVGDefs",
            branch("Gradient", leaf("Timed", 3400), leaf("Tracked", 2854), leaf("Gradient files", 138)),
            leaf("Iteration", 56),
            leaf("Pattern", 645),
            leaf("SVGDefs files", 1205),
        ),
        branch("ScanlineAnimation", leaf("Keyframes", 259)),
        branch("ScrambleText", leaf("Glyphs", 37), leaf("Weights", 37)),
        branch("Staircase", leaf("Indents", 49)),
    ),
    leaf("Utils", 112),
    leaf("src files", 1018),
);
