import type { TreemapNode } from "@thewaver/ss-components";

const leaf = (value: string, weight: number): TreemapNode<string> => ({ value, weight });

const branch = (value: string, ...children: TreemapNode<string>[]): TreemapNode<string> => ({ value, children });

export const formatLines = (lines: number) => `${lines.toLocaleString("en-US")} lines`;

export const LIBRARY: TreemapNode<string> = branch(
    "src",
    branch(
        "Abstracts",
        leaf("Anchor", 520),
        leaf("Carrier", 580),
        leaf("CheckedState", 25),
        leaf("ColorExtractor", 86),
        leaf("Cutout", 56),
        leaf("DateTimeValue", 109),
        leaf("DateValue", 568),
        leaf("Dismisser", 151),
        leaf("ElementFader", 164),
        leaf("ElementObserver", 407),
        leaf("Elevation", 95),
        leaf("Flattener", 124),
        leaf("FocusManager", 250),
        leaf("FrameRateMonitor", 84),
        leaf("Glass", 298),
        leaf("HoverIntent", 334),
        leaf("InteractionTracker", 900),
        leaf("LiveAnnouncer", 98),
        leaf("MaskedField", 144),
        leaf("MediaQueryMonitor", 106),
        leaf("Navigator", 264),
        leaf("Placement", 758),
        leaf("PointerTracker", 197),
        leaf("Proximity", 332),
        leaf("Rotator", 347),
        branch("SVG", leaf("Defs", 1014)),
        leaf("Selection", 232),
        leaf("SignalMirror", 209),
        leaf("TextSync", 397),
        leaf("Typeahead", 164),
        leaf("Viewport", 137),
        leaf("Virtualizer", 178),
    ),
    branch("Composites", leaf("GlassSurface", 188), leaf("Surface", 178)),
    branch(
        "Essentials",
        branch("Accordions", leaf("Accordion", 236), leaf("Collapsible", 285)),
        leaf("AudioSwitcher", 211),
        leaf("Breadcrumbs", 203),
        leaf("Button", 200),
        branch("Carousels", leaf("DrumCarousel", 5), leaf("TrackCarousel", 5)),
        leaf("Drawer", 19),
        leaf("Form", 111),
        leaf("HoverCard", 300),
        leaf("ImageSwitcher", 130),
        branch(
            "Input",
            leaf("Calendar", 738),
            leaf("Checkbox", 53),
            leaf("CheckboxGroup", 168),
            leaf("Clock", 568),
            leaf("ColorArea", 288),
            leaf("ColorInput", 357),
            leaf("CurrencyInput", 112),
            leaf("DateInput", 249),
            leaf("DatePicker", 193),
            leaf("DateRangePicker", 240),
            leaf("DateTimePicker", 148),
            leaf("FileInput", 496),
            leaf("FormField", 185),
            leaf("FormSection", 126),
            leaf("Label", 122),
            leaf("Listbox", 888),
            leaf("MultiListbox", 46),
            leaf("MultiSelect", 62),
            leaf("NumberInput", 486),
            leaf("Radio", 75),
            leaf("RadioGroup", 333),
            leaf("Range", 625),
            leaf("RangeCalendar", 73),
            leaf("Select", 631),
            leaf("TagInput", 323),
            leaf("TextArea", 18),
            leaf("TextInput", 189),
            leaf("TimeInput", 221),
            leaf("TimePicker", 188),
            leaf("Toggle", 23),
        ),
        leaf("Menubar", 9),
        branch("Menus", leaf("FanMenu", 41), leaf("Menu", 1433), leaf("WheelMenu", 172)),
        leaf("Modal", 327),
        leaf("Paginator", 473),
        leaf("Preview", 262),
        leaf("Progress", 174),
        leaf("Scroller", 284),
        leaf("SlideButton", 450),
        leaf("Sortable", 958),
        leaf("SplitPane", 359),
        branch("Spotlights", leaf("SpotlightGuide", 5), leaf("SpotlightHint", 5), leaf("SpotlightPrompt", 5)),
        leaf("Stepper", 332),
        leaf("Table", 1153),
        leaf("Tabs", 445),
        leaf("Toasts", 591),
        leaf("Toolbar", 564),
        leaf("Tooltip", 220),
        leaf("Tree", 638),
        leaf("ViewportWrapper", 156),
    ),
    branch(
        "Exotics",
        leaf("Bracket", 495),
        leaf("CardStack", 370),
        leaf("CellAnimation", 424),
        leaf("Corners", 134),
        leaf("Cuboid", 289),
        leaf("FlipCard", 114),
        leaf("Formation", 62),
        branch("Mosaics", leaf("ElementMosaic", 52), leaf("ImageMosaic", 126)),
        leaf("Odometer", 349),
        leaf("ParticleSpawner", 352),
        leaf("PatchBoard", 1526),
        branch("PointerEffects", leaf("LightCatcher", 149), leaf("ShadowCaster", 182), leaf("Tilter", 207)),
        branch("Reveals", leaf("Reveal", 138), leaf("ScratchCard", 552)),
        leaf("RichText", 211),
        leaf("Satellite", 163),
        leaf("ScanlineAnimation", 40),
        leaf("ScrambleText", 314),
        leaf("Shape", 216),
        leaf("SortableGrid", 1531),
        leaf("Staircase", 105),
        leaf("TileBoard", 951),
        leaf("Timeline", 1006),
        leaf("Trail", 303),
        leaf("Treemap", 675),
        leaf("Typewriter", 321),
        branch("Wheels", leaf("DrumWheel", 5), leaf("OverheadWheel", 5)),
    ),
    branch(
        "Primitives",
        leaf("Barrel", 311),
        leaf("BinarySwitch", 189),
        leaf("Carousel", 638),
        leaf("InteractionWrapper", 246),
        leaf("Mosaic", 609),
        leaf("PlacementBox", 151),
        leaf("PlacementItem", 98),
        leaf("Popover", 260),
        leaf("PopupTrigger", 74),
        leaf("Spotlight", 389),
        leaf("TextField", 587),
        leaf("Wheel", 429),
    ),
    branch(
        "Samples",
        branch("Bracket", leaf("Connectors", 212)),
        branch(
            "CellAnimation",
            leaf("Breakpoints", 98),
            leaf("Keyframes", 1944),
            leaf("Origins", 32),
            leaf("Playback", 43),
            leaf("Weights", 1634),
            leaf("Zones", 77),
        ),
        branch("Placement", leaf("Layouts", 991)),
        branch("Proximity", leaf("Effects", 325)),
        branch(
            "SVGDefs",
            leaf("Gradient", 6940),
            leaf("Iteration", 60),
            leaf("Pattern", 655),
            leaf("SVGDefs files", 1165),
        ),
        branch("ScanlineAnimation", leaf("Keyframes", 379)),
        branch("Staircase", leaf("Indents", 51)),
        leaf("Samples files", 21),
    ),
    leaf("Utils", 86),
    leaf("src files", 696),
);
