import type { TreemapNode } from "@thewaver/ss-components";

const leaf = (value: string, weight: number): TreemapNode<string> => ({ value, weight });

const branch = (value: string, ...children: TreemapNode<string>[]): TreemapNode<string> => ({ value, children });

export const formatLines = (lines: number) => `${lines.toLocaleString("en-US")} lines`;

export const LIBRARY: TreemapNode<string> = branch(
    "src",
    branch(
        "Abstracts",
        leaf("Anchor", 535),
        leaf("Carrier", 578),
        leaf("CheckedState", 23),
        leaf("ColorExtractor", 84),
        leaf("Cutout", 54),
        leaf("DateTimeValue", 107),
        leaf("DateValue", 566),
        leaf("Dismisser", 149),
        leaf("ElementFader", 163),
        leaf("ElementObserver", 530),
        leaf("Elevation", 94),
        leaf("Flattener", 122),
        leaf("FocusManager", 249),
        leaf("FrameRateMonitor", 83),
        leaf("Glass", 298),
        leaf("HoverIntent", 332),
        leaf("InteractionTracker", 899),
        leaf("LiveAnnouncer", 96),
        leaf("MaskedField", 142),
        leaf("MediaQueryMonitor", 105),
        leaf("Navigator", 262),
        leaf("Placement", 756),
        leaf("PointerTracker", 195),
        leaf("Proximity", 330),
        leaf("Rotator", 346),
        leaf("Selection", 230),
        leaf("SignalMirror", 208),
        leaf("Smoother", 102),
        leaf("TextSync", 424),
        leaf("Typeahead", 162),
        leaf("Viewport", 134),
        leaf("Virtualizer", 176),
    ),
    branch("Composites", leaf("GlassSurface", 185), leaf("Surface", 175)),
    branch(
        "Essentials",
        branch("Accordions", leaf("Accordion", 232), leaf("Collapsible", 320)),
        leaf("AudioSwitcher", 234),
        leaf("Breadcrumbs", 199),
        leaf("Button", 196),
        branch("Carousels", leaf("DrumCarousel", 4), leaf("TrackCarousel", 4)),
        leaf("Drawer", 20),
        leaf("EdgeFader", 208),
        leaf("Form", 107),
        leaf("HoverCard", 298),
        leaf("ImageSwitcher", 126),
        branch(
            "Input",
            leaf("Calendar", 733),
            leaf("Checkbox", 51),
            leaf("CheckboxGroup", 162),
            leaf("Clock", 563),
            leaf("ColorArea", 285),
            leaf("ColorInput", 353),
            leaf("CurrencyInput", 109),
            leaf("DateInput", 246),
            leaf("DatePicker", 190),
            leaf("DateRangePicker", 246),
            leaf("DateTimePicker", 152),
            leaf("FileInput", 491),
            leaf("FormField", 184),
            leaf("FormSection", 122),
            leaf("Label", 115),
            leaf("Listbox", 894),
            leaf("MultiListbox", 44),
            leaf("MultiSelect", 60),
            leaf("NumberInput", 482),
            leaf("Radio", 73),
            leaf("RadioGroup", 327),
            leaf("Range", 620),
            leaf("RangeCalendar", 72),
            leaf("SegmentedInput", 254),
            leaf("Select", 626),
            leaf("TagInput", 319),
            leaf("TextArea", 16),
            leaf("TextInput", 187),
            leaf("TimeInput", 219),
            leaf("TimePicker", 185),
            leaf("Toggle", 21),
        ),
        leaf("Menubar", 7),
        branch("Menus", leaf("FanMenu", 39), leaf("Menu", 1437), leaf("WheelMenu", 169)),
        leaf("Modal", 323),
        leaf("Paginator", 468),
        leaf("Preview", 258),
        leaf("Progress", 170),
        leaf("Scroller", 280),
        leaf("Sidebar", 267),
        leaf("SlideButton", 445),
        leaf("Sortable", 954),
        leaf("SplitPane", 379),
        branch("Spotlights", leaf("SpotlightGuide", 4), leaf("SpotlightHint", 4), leaf("SpotlightPrompt", 4)),
        leaf("Stepper", 328),
        leaf("Table", 1147),
        leaf("TableOfContents", 300),
        leaf("Tabs", 458),
        leaf("Toasts", 602),
        leaf("Toolbar", 559),
        leaf("Tooltip", 218),
        leaf("Tree", 634),
        leaf("ViewportWrapper", 153),
    ),
    branch(
        "Exotics",
        leaf("Bracket", 603),
        leaf("CardStack", 478),
        leaf("CellAnimation", 464),
        leaf("CirclePacking", 952),
        leaf("Corners", 132),
        leaf("Cuboid", 876),
        leaf("Die", 730),
        leaf("FlipCard", 170),
        leaf("Formation", 96),
        leaf("Icicle", 597),
        branch("Mosaics", leaf("ElementMosaic", 67), leaf("ImageMosaic", 131)),
        leaf("Odometer", 628),
        leaf("ParticleField", 526),
        leaf("ParticleSpawner", 463),
        leaf("PatchBoard", 1685),
        branch("PointerEffects", leaf("LightCatcher", 167), leaf("ShadowCaster", 194), leaf("Tilter", 230)),
        branch("Reveals", leaf("Reveal", 210), leaf("ScratchCard", 547)),
        leaf("RichText", 303),
        leaf("Satellite", 212),
        leaf("ScanlineAnimation", 59),
        leaf("ScrambleText", 407),
        leaf("Shape", 222),
        leaf("SortableGrid", 1676),
        leaf("Staircase", 103),
        leaf("Sunburst", 603),
        leaf("TileBoard", 1189),
        leaf("Timeline", 1544),
        leaf("Trail", 381),
        leaf("Treemap", 667),
        leaf("Typewriter", 429),
        branch("Wheels", leaf("DrumWheel", 4), leaf("OverheadWheel", 4)),
    ),
    branch(
        "Generators",
        leaf("CellAnimationBreakpoints", 141),
        leaf("CellAnimationKeyframes", 231),
        leaf("CellAnimationPlayback", 80),
        leaf("CellAnimationWeights", 616),
        leaf("CellAnimationZones", 129),
        leaf("PlacementLayouts", 732),
        leaf("ProximityEffects", 230),
        branch(
            "SVGDefs",
            leaf("SVGAnimations", 147),
            leaf("SVGFilters", 732),
            leaf("SVGGradients", 204),
            leaf("SVGPatterns", 44),
            leaf("SVGDefs files", 26),
        ),
    ),
    branch(
        "Primitives",
        leaf("Barrel", 306),
        leaf("BinarySwitch", 186),
        leaf("Carousel", 635),
        leaf("InteractionWrapper", 242),
        leaf("Mosaic", 1014),
        leaf("PlacementBox", 166),
        leaf("PlacementItem", 155),
        leaf("Popover", 256),
        leaf("PopupTrigger", 78),
        leaf("Spotlight", 384),
        leaf("TextField", 608),
        leaf("Wheel", 427),
    ),
    branch(
        "Samples",
        branch("Bracket", leaf("Connectors", 209)),
        branch(
            "CellAnimation",
            branch("Keyframes", leaf("Samples", 1286), leaf("Keyframes files", 378)),
            leaf("Origins", 31),
            branch("Weights", leaf("Samples", 917), leaf("Weights files", 252)),
        ),
        branch("Die", leaf("Shapes", 81)),
        branch("Odometer", leaf("Reels", 78)),
        branch("PatchBoard", leaf("Snaps", 12)),
        branch("Placement", leaf("Layouts", 18)),
        branch("Proximity", leaf("Effects", 13)),
        branch(
            "SVGDefs",
            branch("Gradient", leaf("Timed", 3391), leaf("Tracked", 2898), leaf("Gradient files", 138)),
            leaf("Iteration", 56),
            leaf("Pattern", 645),
            leaf("SVGDefs files", 1175),
        ),
        branch("ScanlineAnimation", leaf("Keyframes", 259)),
        branch("ScrambleText", leaf("Glyphs", 37), leaf("Weights", 37)),
        branch("Staircase", leaf("Indents", 49)),
    ),
    leaf("Utils", 84),
    leaf("src files", 746),
);
