import type { TreemapNode } from "@thewaver/ss-components";

const leaf = (value: string, weight: number): TreemapNode<string> => ({ value, weight });

const branch = (value: string, ...children: TreemapNode<string>[]): TreemapNode<string> => ({ value, children });

export const formatLines = (lines: number) => `${lines.toLocaleString("en-US")} lines`;

export const LIBRARY: TreemapNode<string> = branch(
    "src",
    branch(
        "Abstracts",
        leaf("Anchor", 616),
        leaf("Carrier", 680),
        leaf("CheckedState", 23),
        leaf("ColorExtractor", 152),
        leaf("Cutout", 65),
        leaf("DateTimeValue", 113),
        leaf("DateValue", 566),
        leaf("Dismisser", 183),
        leaf("ElementFader", 242),
        leaf("ElementObserver", 754),
        leaf("Elevation", 127),
        leaf("Flattener", 122),
        leaf("FocusManager", 269),
        leaf("FrameRateMonitor", 120),
        leaf("Glass", 308),
        leaf("HoverIntent", 409),
        leaf("InteractionTracker", 1195),
        leaf("LiveAnnouncer", 96),
        leaf("MaskedField", 210),
        leaf("MediaQueryMonitor", 165),
        leaf("Navigator", 326),
        leaf("Placement", 756),
        leaf("PointerTracker", 255),
        leaf("Proximity", 330),
        leaf("Rotator", 506),
        leaf("Selection", 265),
        leaf("SignalMirror", 292),
        leaf("Smoother", 141),
        leaf("TextSync", 472),
        leaf("Typeahead", 199),
        leaf("Viewport", 132),
        leaf("Virtualizer", 228),
    ),
    branch("Composites", leaf("GlassSurface", 153), leaf("Surface", 253)),
    branch(
        "Essentials",
        branch("Accordions", leaf("Accordion", 295), leaf("Collapsible", 406)),
        leaf("AudioSwitcher", 283),
        leaf("Breadcrumbs", 198),
        leaf("Button", 196),
        branch("Carousels", leaf("DrumCarousel", 4), leaf("TrackCarousel", 4)),
        leaf("Drawer", 21),
        leaf("EdgeFader", 294),
        leaf("Form", 152),
        leaf("HoverCard", 403),
        leaf("ImageSwitcher", 178),
        branch(
            "Input",
            leaf("Calendar", 945),
            leaf("Checkbox", 51),
            leaf("CheckboxGroup", 222),
            leaf("Clock", 727),
            leaf("ColorArea", 374),
            leaf("ColorInput", 444),
            leaf("CurrencyInput", 208),
            leaf("DateInput", 371),
            leaf("DatePicker", 192),
            leaf("DateRangePicker", 272),
            leaf("DateTimePicker", 177),
            leaf("FileInput", 581),
            leaf("FormField", 204),
            leaf("FormSection", 126),
            leaf("Label", 146),
            leaf("Listbox", 1243),
            leaf("MultiListbox", 44),
            leaf("MultiSelect", 61),
            leaf("NumberInput", 571),
            leaf("Radio", 73),
            leaf("RadioGroup", 511),
            leaf("Range", 803),
            leaf("RangeCalendar", 118),
            leaf("SegmentedInput", 372),
            leaf("Select", 698),
            leaf("TagInput", 434),
            leaf("TextArea", 16),
            leaf("TextInput", 183),
            leaf("TimeInput", 375),
            leaf("TimePicker", 189),
            leaf("Toggle", 21),
        ),
        leaf("Menubar", 7),
        branch("Menus", leaf("FanMenu", 57), leaf("Menu", 1883), leaf("WheelMenu", 266)),
        leaf("Modal", 430),
        leaf("Paginator", 525),
        leaf("Preview", 294),
        leaf("Progress", 212),
        leaf("Scroller", 388),
        leaf("Sidebar", 311),
        leaf("SlideButton", 518),
        leaf("Sortable", 1288),
        leaf("SplitPane", 618),
        branch("Spotlights", leaf("SpotlightGuide", 4), leaf("SpotlightHint", 4), leaf("SpotlightPrompt", 4)),
        leaf("Stepper", 371),
        leaf("Table", 1525),
        leaf("TableOfContents", 359),
        leaf("Tabs", 594),
        leaf("Toasts", 752),
        leaf("Toolbar", 805),
        leaf("Tooltip", 231),
        leaf("Tree", 781),
        leaf("ViewportWrapper", 231),
    ),
    branch(
        "Exotics",
        leaf("Bracket", 772),
        leaf("CardStack", 695),
        leaf("CellAnimation", 651),
        leaf("CirclePacking", 921),
        leaf("Corners", 162),
        leaf("Cuboid", 1030),
        leaf("Die", 899),
        leaf("FlipCard", 270),
        leaf("Formation", 97),
        leaf("Icicle", 596),
        branch("Mosaics", leaf("ElementMosaic", 65), leaf("ImageMosaic", 197)),
        leaf("Odometer", 750),
        leaf("ParticleField", 594),
        leaf("ParticleSpawner", 615),
        leaf("PatchBoard", 1925),
        branch(
            "PointerEffects",
            leaf("LightCatcher", 137),
            leaf("ShadowCaster", 148),
            leaf("Tilter", 185),
            leaf("PointerEffects files", 236),
        ),
        branch("Reveals", leaf("Reveal", 339), leaf("ScratchCard", 661)),
        leaf("RichText", 341),
        leaf("Satellite", 211),
        leaf("ScanlineAnimation", 63),
        leaf("ScrambleText", 513),
        leaf("Shape", 278),
        leaf("SortableGrid", 1903),
        leaf("Staircase", 155),
        leaf("Sunburst", 574),
        leaf("TileBoard", 1284),
        leaf("Timeline", 1805),
        leaf("Trail", 437),
        leaf("Treemap", 877),
        leaf("Typewriter", 661),
        branch("Wheels", leaf("DrumWheel", 4), leaf("OverheadWheel", 4)),
    ),
    branch(
        "Generators",
        leaf("CellAnimationBreakpoints", 141),
        leaf("CellAnimationKeyframes", 231),
        leaf("CellAnimationPlayback", 80),
        leaf("CellAnimationWeights", 616),
        leaf("CellAnimationZones", 129),
        leaf("PlacementLayouts", 732),
        leaf("ProximityEffects", 230),
        branch(
            "SVGDefs",
            leaf("SVGAnimations", 224),
            leaf("SVGFilters", 922),
            leaf("SVGGradients", 281),
            leaf("SVGPatterns", 83),
            leaf("SVGDefs files", 25),
        ),
    ),
    branch(
        "Primitives",
        leaf("Barrel", 316),
        leaf("BinarySwitch", 234),
        leaf("Carousel", 849),
        leaf("InteractionWrapper", 246),
        leaf("Mosaic", 1162),
        leaf("PlacementBox", 250),
        leaf("PlacementItem", 242),
        leaf("Popover", 292),
        leaf("PopupTrigger", 79),
        leaf("Spotlight", 436),
        leaf("TextField", 721),
        leaf("Wheel", 584),
    ),
    branch(
        "Samples",
        branch("Bracket", leaf("Connectors", 213)),
        branch(
            "CellAnimation",
            branch("Keyframes", leaf("Samples", 1286), leaf("Keyframes files", 378)),
            leaf("Origins", 31),
            branch("Weights", leaf("Samples", 917), leaf("Weights files", 252)),
        ),
        branch("Die", leaf("Shapes", 81)),
        branch("Odometer", leaf("Reels", 78)),
        branch("PatchBoard", leaf("Snaps", 12)),
        branch("Placement", leaf("Layouts", 18)),
        branch("Proximity", leaf("Effects", 13)),
        branch(
            "SVGDefs",
            branch("Gradient", leaf("Timed", 3417), leaf("Tracked", 2951), leaf("Gradient files", 138)),
            leaf("Iteration", 56),
            leaf("Pattern", 645),
            leaf("SVGDefs files", 1224),
        ),
        branch("ScanlineAnimation", leaf("Keyframes", 259)),
        branch("ScrambleText", leaf("Glyphs", 37), leaf("Weights", 37)),
        branch("Staircase", leaf("Indents", 49)),
    ),
    leaf("Utils", 112),
    leaf("src files", 1018),
);
