<script setup lang="ts">
import { shallowRef } from "vue";

import {
    LONG_TEXT,
    MAX_ROWS,
    MIN_ROWS,
    REVIEW_LIMIT,
} from "@thewaver/ss-playground/App/Pages/TextAreaPage/TextAreaPage.const";

import type { ExampleDefs } from "../../PageComponents/Examples/Examples.types";
import PageExamples from "../../PageComponents/Examples/PageExamples.vue";
import AutoSizingExample from "./Examples/AutoSizing.vue";
import AutoSizingCappedExample from "./Examples/AutoSizingCapped.vue";
import DisabledExample from "./Examples/Disabled.vue";
import ErroredExample from "./Examples/Errored.vue";
import FixedHeightExample from "./Examples/FixedHeight.vue";
import LabeledExample from "./Examples/Labeled.vue";
import ReachableExample from "./Examples/Reachable.vue";
import ReadOnlyExample from "./Examples/ReadOnly.vue";

const EXAMPLES_ROOT = "/src/App/Pages/TextAreaPage/Examples";

const fixedValue = shallowRef("");
const growingValue = shallowRef("");
const cappedValue = shallowRef(LONG_TEXT);
const readOnlyValue = shallowRef("Generated by the server,\nacross two lines.");
const disabledValue = shallowRef("Cannot be edited");
const reachableValue = shallowRef("Cannot be edited either");
const erroredValue = shallowRef("Too short");
const labeledValue = shallowRef("");

const examples: ExampleDefs[] = [
    {
        key: "fixedHeight",
        name: "Fixed height",
        readout: () => `length: ${fixedValue.value.length} — the painter sizes the box and it stays put`,
        path: `${EXAMPLES_ROOT}/FixedHeight.vue`,
    },
    {
        key: "autoSizing",
        name: "Auto-sizing",
        readout: () =>
            `length: ${growingValue.value.length} — grows from ${MIN_ROWS} rows with no ceiling, so it never scrolls`,
        path: `${EXAMPLES_ROOT}/AutoSizing.vue`,
    },
    {
        key: "autoSizingCapped",
        name: "Auto-sizing, capped",
        readout: () => `length: ${cappedValue.value.length} — stops growing at ${MAX_ROWS} rows and scrolls`,
        path: `${EXAMPLES_ROOT}/AutoSizingCapped.vue`,
    },
    {
        key: "readOnly",
        name: "Read-only",
        readout: () => `length: ${readOnlyValue.value.length} — selectable and copyable, never editable`,
        path: `${EXAMPLES_ROOT}/ReadOnly.vue`,
    },
    {
        key: "disabled",
        name: "Disabled",
        readout: () => `length: ${disabledValue.value.length}`,
        path: `${EXAMPLES_ROOT}/Disabled.vue`,
    },
    {
        key: "reachable",
        name: "Disabled + reachable",
        readout: () => `length: ${reachableValue.value.length}`,
        path: `${EXAMPLES_ROOT}/Reachable.vue`,
    },
    {
        key: "errored",
        name: "Error",
        readout: () => `length: ${erroredValue.value.length} — fewer than ${REVIEW_LIMIT} characters is an error`,
        path: `${EXAMPLES_ROOT}/Errored.vue`,
    },
    {
        key: "label",
        name: "In a Label",
        readout: () => `length: ${labeledValue.value.length}`,
        path: `${EXAMPLES_ROOT}/Labeled.vue`,
    },
];
</script>

<template>
    <PageExamples :items="examples" :min-column-width="400">
        <template #fixedHeight>
            <FixedHeightExample v-model:value="fixedValue" />
        </template>

        <template #autoSizing>
            <AutoSizingExample v-model:value="growingValue" />
        </template>

        <template #autoSizingCapped>
            <AutoSizingCappedExample v-model:value="cappedValue" />
        </template>

        <template #readOnly>
            <ReadOnlyExample v-model:value="readOnlyValue" />
        </template>

        <template #disabled>
            <DisabledExample v-model:value="disabledValue" />
        </template>

        <template #reachable>
            <ReachableExample v-model:value="reachableValue" />
        </template>

        <template #errored>
            <ErroredExample v-model:value="erroredValue" />
        </template>

        <template #label>
            <LabeledExample v-model:value="labeledValue" />
        </template>
    </PageExamples>
</template>
