import { createMemo, createSignal } from "solid-js";

import { PageExamples } from "../../PageComponents/Examples/Examples";
import { AutoSizingExample } from "./Examples/AutoSizing";
import { AutoSizingCappedExample } from "./Examples/AutoSizingCapped";
import { DisabledExample } from "./Examples/Disabled";
import { ErroredExample } from "./Examples/Errored";
import { FixedHeightExample } from "./Examples/FixedHeight";
import { LabelledExample } from "./Examples/Labelled";
import { ReachableExample } from "./Examples/Reachable";
import { ReadOnlyExample } from "./Examples/ReadOnly";
import { LONG_TEXT, MAX_ROWS, MIN_ROWS, REVIEW_LIMIT } from "./TextAreaPage.const";

const MIN_COLUMN_WIDTH = 340;
const EXAMPLES_ROOT = "/src/App/Pages/TextAreaPage/Examples";

export const TextAreaPage = () => {
    const fixedSignal = createSignal("");
    const growingSignal = createSignal("");
    const cappedSignal = createSignal(LONG_TEXT);
    const readOnlySignal = createSignal("Generated by the server,\nacross two lines.");
    const disabledSignal = createSignal("Cannot be edited");
    const reachableSignal = createSignal("Cannot be edited either");
    const erroredSignal = createSignal("Too short");
    const labelledSignal = createSignal("");

    const getExamples = createMemo(() => [
        {
            key: "fixedHeight",
            name: "Fixed height",
            readout: () => `length: ${fixedSignal[0]().length} — the painter sizes the box and it stays put`,
            component: () => <FixedHeightExample valueSignal={fixedSignal} />,
            path: `${EXAMPLES_ROOT}/FixedHeight.tsx`,
        },
        {
            key: "autoSizing",
            name: "Auto-sizing",
            readout: () =>
                `length: ${growingSignal[0]().length} — grows from ${MIN_ROWS} rows with no ceiling, so it never scrolls`,
            component: () => <AutoSizingExample valueSignal={growingSignal} />,
            path: `${EXAMPLES_ROOT}/AutoSizing.tsx`,
        },
        {
            key: "autoSizingCapped",
            name: "Auto-sizing, capped",
            readout: () => `length: ${cappedSignal[0]().length} — stops growing at ${MAX_ROWS} rows and scrolls`,
            component: () => <AutoSizingCappedExample valueSignal={cappedSignal} />,
            path: `${EXAMPLES_ROOT}/AutoSizingCapped.tsx`,
        },
        {
            key: "readOnly",
            name: "Read-only",
            readout: () => `length: ${readOnlySignal[0]().length} — selectable and copyable, never editable`,
            component: () => <ReadOnlyExample valueSignal={readOnlySignal} />,
            path: `${EXAMPLES_ROOT}/ReadOnly.tsx`,
        },
        {
            key: "disabled",
            name: "Disabled",
            readout: () => `length: ${disabledSignal[0]().length}`,
            component: () => <DisabledExample valueSignal={disabledSignal} />,
            path: `${EXAMPLES_ROOT}/Disabled.tsx`,
        },
        {
            key: "reachable",
            name: "Disabled + reachable",
            readout: () => `length: ${reachableSignal[0]().length}`,
            component: () => <ReachableExample valueSignal={reachableSignal} />,
            path: `${EXAMPLES_ROOT}/Reachable.tsx`,
        },
        {
            key: "errored",
            name: "Error",
            readout: () => `length: ${erroredSignal[0]().length} — fewer than ${REVIEW_LIMIT} characters is an error`,
            component: () => <ErroredExample valueSignal={erroredSignal} />,
            path: `${EXAMPLES_ROOT}/Errored.tsx`,
        },
        {
            key: "label",
            name: "In a Label",
            readout: () => `length: ${labelledSignal[0]().length}`,
            component: () => <LabelledExample valueSignal={labelledSignal} />,
            path: `${EXAMPLES_ROOT}/Labelled.tsx`,
        },
    ]);

    return <PageExamples items={getExamples} minColumnWidth={() => MIN_COLUMN_WIDTH} />;
};
