<script lang="ts">
    import {
        CITIES,
        PIN_LENGTH,
        QUANTITY_STEP,
    } from "@thewaver/ss-playground/App/Pages/TextInputPage/TextInputPage.const";

    import type { ExampleDefs } from "../../PageComponents/Examples/Examples.types";
    import PageExamples from "../../PageComponents/Examples/PageExamples.svelte";
    import BothAdornmentsExample from "./Examples/BothAdornments.svelte";
    import CitiesExample from "./Examples/Cities.svelte";
    import DefaultExample from "./Examples/Default.svelte";
    import DisabledExample from "./Examples/Disabled.svelte";
    import EditableExample from "./Examples/Editable.svelte";
    import ErroredExample from "./Examples/Errored.svelte";
    import LabeledExample from "./Examples/Labeled.svelte";
    import NumberFieldExample from "./Examples/NumberField.svelte";
    import PasswordExample from "./Examples/Password.svelte";
    import ReachableExample from "./Examples/Reachable.svelte";
    import ReadOnlyExample from "./Examples/ReadOnly.svelte";
    import RefusingSetterExample from "./Examples/RefusingSetter.svelte";
    import TransformingSetterExample from "./Examples/TransformingSetter.svelte";

    const EXAMPLES_ROOT = "/src/App/Pages/TextInputPage/Examples";

    let defaultValue = $state("");
    let passwordValue = $state("");
    let readOnlyValue = $state("Generated by the server");
    let disabledValue = $state("Cannot be edited");
    let reachableValue = $state("Cannot be edited either");
    let erroredValue = $state("not-an-email");
    let labeledValue = $state("");
    let codeValue = $state("");
    let pinValue = $state("");
    let amountValue = $state("");
    let quantityValue = $state("10");
    let isRevealed = $state(false);
    let cityValue = $state("");
    let editableValue = $state("Ada Lovelace");
    let isEditing = $state(false);

    const citySuggestions = $derived.by(() => {
        const query = cityValue.trim().toLocaleLowerCase();

        if (!query) return [];

        return CITIES.filter((city) => city.name.toLocaleLowerCase().startsWith(query));
    });

    const examples: ExampleDefs[] = [
        {
            key: "default",
            name: "Default",
            readout: () => `value: "${defaultValue}"`,
            component: defaultExample,
            path: `${EXAMPLES_ROOT}/Default.svelte`,
        },
        {
            key: "transformingSetter",
            name: "Transforming setter",
            readout: () => `value: "${codeValue}" — type lowercase mid-string, the caret must not jump`,
            component: transformingSetterExample,
            path: `${EXAMPLES_ROOT}/TransformingSetter.svelte`,
        },
        {
            key: "refusingSetter",
            name: "Refusing setter",
            readout: () => `value: "${pinValue}" — letters are refused, ${PIN_LENGTH} digits max`,
            component: refusingSetterExample,
            path: `${EXAMPLES_ROOT}/RefusingSetter.svelte`,
        },
        {
            key: "suggestions",
            name: "Suggestions",
            readout: () =>
                `value: "${cityValue}" — ${citySuggestions.length} suggested; any text is kept, and Enter only picks once the arrows have moved into the list`,
            component: citiesExample,
            path: `${EXAMPLES_ROOT}/Cities.svelte`,
        },
        {
            key: "editable",
            name: "Edit in place",
            readout: () =>
                `value: "${editableValue}" | editing: ${isEditing} — Enter or leaving keeps the edit, Escape puts the old text back`,
            component: editableExample,
            path: `${EXAMPLES_ROOT}/Editable.svelte`,
        },
        {
            key: "password",
            name: "Password",
            readout: () => `value: "${passwordValue}" | revealed: ${isRevealed}`,
            component: passwordExample,
            path: `${EXAMPLES_ROOT}/Password.svelte`,
        },
        {
            key: "bothAdornments",
            name: "Both adornments",
            readout: () => `value: "${amountValue}"`,
            component: bothAdornmentsExample,
            path: `${EXAMPLES_ROOT}/BothAdornments.svelte`,
        },
        {
            key: "number",
            name: "Number",
            readout: () => `value: "${quantityValue}" — arrows step by ${QUANTITY_STEP}, no spinner buttons`,
            component: numberFieldExample,
            path: `${EXAMPLES_ROOT}/NumberField.svelte`,
        },
        {
            key: "readOnly",
            name: "Read-only",
            readout: () => `value: "${readOnlyValue}" — selectable and copyable, never editable`,
            component: readOnlyExample,
            path: `${EXAMPLES_ROOT}/ReadOnly.svelte`,
        },
        {
            key: "disabled",
            name: "Disabled",
            readout: () => `value: "${disabledValue}"`,
            component: disabledExample,
            path: `${EXAMPLES_ROOT}/Disabled.svelte`,
        },
        {
            key: "reachable",
            name: "Disabled + reachable",
            readout: () => `value: "${reachableValue}"`,
            component: reachableExample,
            path: `${EXAMPLES_ROOT}/Reachable.svelte`,
        },
        {
            key: "errored",
            name: "Error",
            readout: () => `value: "${erroredValue}"`,
            component: erroredExample,
            path: `${EXAMPLES_ROOT}/Errored.svelte`,
        },
        {
            key: "label",
            name: "In a Label",
            readout: () => `value: "${labeledValue}"`,
            component: labeledExample,
            path: `${EXAMPLES_ROOT}/Labeled.svelte`,
        },
    ];
</script>

{#snippet defaultExample()}
    <DefaultExample bind:value={defaultValue} />
{/snippet}

{#snippet transformingSetterExample()}
    <TransformingSetterExample bind:value={codeValue} />
{/snippet}

{#snippet refusingSetterExample()}
    <RefusingSetterExample bind:value={pinValue} />
{/snippet}

{#snippet citiesExample()}
    <CitiesExample bind:value={cityValue} suggestions={citySuggestions} />
{/snippet}

{#snippet editableExample()}
    <EditableExample bind:value={editableValue} bind:editing={isEditing} />
{/snippet}

{#snippet passwordExample()}
    <PasswordExample bind:value={passwordValue} bind:reveal={isRevealed} />
{/snippet}

{#snippet bothAdornmentsExample()}
    <BothAdornmentsExample bind:value={amountValue} />
{/snippet}

{#snippet numberFieldExample()}
    <NumberFieldExample bind:value={quantityValue} />
{/snippet}

{#snippet readOnlyExample()}
    <ReadOnlyExample bind:value={readOnlyValue} />
{/snippet}

{#snippet disabledExample()}
    <DisabledExample bind:value={disabledValue} />
{/snippet}

{#snippet reachableExample()}
    <ReachableExample bind:value={reachableValue} />
{/snippet}

{#snippet erroredExample()}
    <ErroredExample bind:value={erroredValue} />
{/snippet}

{#snippet labeledExample()}
    <LabeledExample bind:value={labeledValue} />
{/snippet}

<PageExamples items={examples} />
