import { useMemo, useState } from "react";

import { CITIES, PIN_LENGTH, QUANTITY_STEP } from "@thewaver/ss-playground/App/Pages/TextInputPage/TextInputPage.const";

import { PageExamples } from "../../PageComponents/Examples/Examples";
import { BothAdornmentsExample } from "./Examples/BothAdornments";
import { CitiesExample } from "./Examples/Cities";
import { DefaultExample } from "./Examples/Default";
import { DisabledExample } from "./Examples/Disabled";
import { EditableExample } from "./Examples/Editable";
import { ErroredExample } from "./Examples/Errored";
import { LabeledExample } from "./Examples/Labeled";
import { NumberFieldExample } from "./Examples/NumberField";
import { PasswordExample } from "./Examples/Password";
import { ReachableExample } from "./Examples/Reachable";
import { ReadOnlyExample } from "./Examples/ReadOnly";
import { RefusingSetterExample } from "./Examples/RefusingSetter";
import { TransformingSetterExample } from "./Examples/TransformingSetter";

const EXAMPLES_ROOT = "/src/App/Pages/TextInputPage/Examples";

export const TextInputPage = () => {
    const defaultState = useState("");
    const passwordState = useState("");
    const readOnlyState = useState("Generated by the server");
    const disabledState = useState("Cannot be edited");
    const reachableState = useState("Cannot be edited either");
    const erroredState = useState("not-an-email");
    const labeledState = useState("");
    const codeState = useState("");
    const pinState = useState("");
    const amountState = useState("");
    const quantityState = useState("10");
    const revealState = useState(false);
    const cityState = useState("");
    const editableState = useState("Ada Lovelace");
    const editingState = useState(false);

    const citySuggestions = useMemo(() => {
        const query = cityState[0].trim().toLocaleLowerCase();

        if (!query) return [];

        return CITIES.filter((city) => city.name.toLocaleLowerCase().startsWith(query));
    }, [cityState[0]]);

    const examples = [
        {
            key: "default",
            name: "Default",
            readout: () => `value: "${defaultState[0]}"`,
            component: () => <DefaultExample value={defaultState} />,
            path: `${EXAMPLES_ROOT}/Default.tsx`,
        },
        {
            key: "transformingSetter",
            name: "Transforming setter",
            readout: () => `value: "${codeState[0]}" — type lowercase mid-string, the caret must not jump`,
            component: () => <TransformingSetterExample value={codeState} />,
            path: `${EXAMPLES_ROOT}/TransformingSetter.tsx`,
        },
        {
            key: "refusingSetter",
            name: "Refusing setter",
            readout: () => `value: "${pinState[0]}" — letters are refused, ${PIN_LENGTH} digits max`,
            component: () => <RefusingSetterExample value={pinState} />,
            path: `${EXAMPLES_ROOT}/RefusingSetter.tsx`,
        },
        {
            key: "suggestions",
            name: "Suggestions",
            readout: () =>
                `value: "${cityState[0]}" — ${citySuggestions.length} suggested; any text is kept, and Enter only picks once the arrows have moved into the list`,
            component: () => <CitiesExample value={cityState} suggestions={citySuggestions} />,
            path: `${EXAMPLES_ROOT}/Cities.tsx`,
        },
        {
            key: "editable",
            name: "Edit in place",
            readout: () =>
                `value: "${editableState[0]}" | editing: ${editingState[0]} — Enter or leaving keeps the edit, Escape puts the old text back`,
            component: () => <EditableExample value={editableState} editing={editingState} />,
            path: `${EXAMPLES_ROOT}/Editable.tsx`,
        },
        {
            key: "password",
            name: "Password",
            readout: () => `value: "${passwordState[0]}" | revealed: ${revealState[0]}`,
            component: () => <PasswordExample value={passwordState} reveal={revealState} />,
            path: `${EXAMPLES_ROOT}/Password.tsx`,
        },
        {
            key: "bothAdornments",
            name: "Both adornments",
            readout: () => `value: "${amountState[0]}"`,
            component: () => <BothAdornmentsExample value={amountState} />,
            path: `${EXAMPLES_ROOT}/BothAdornments.tsx`,
        },
        {
            key: "number",
            name: "Number",
            readout: () => `value: "${quantityState[0]}" — arrows step by ${QUANTITY_STEP}, no spinner buttons`,
            component: () => <NumberFieldExample value={quantityState} />,
            path: `${EXAMPLES_ROOT}/NumberField.tsx`,
        },
        {
            key: "readOnly",
            name: "Read-only",
            readout: () => `value: "${readOnlyState[0]}" — selectable and copyable, never editable`,
            component: () => <ReadOnlyExample value={readOnlyState} />,
            path: `${EXAMPLES_ROOT}/ReadOnly.tsx`,
        },
        {
            key: "disabled",
            name: "Disabled",
            readout: () => `value: "${disabledState[0]}"`,
            component: () => <DisabledExample value={disabledState} />,
            path: `${EXAMPLES_ROOT}/Disabled.tsx`,
        },
        {
            key: "reachable",
            name: "Disabled + reachable",
            readout: () => `value: "${reachableState[0]}"`,
            component: () => <ReachableExample value={reachableState} />,
            path: `${EXAMPLES_ROOT}/Reachable.tsx`,
        },
        {
            key: "errored",
            name: "Error",
            readout: () => `value: "${erroredState[0]}"`,
            component: () => <ErroredExample value={erroredState} />,
            path: `${EXAMPLES_ROOT}/Errored.tsx`,
        },
        {
            key: "label",
            name: "In a Label",
            readout: () => `value: "${labeledState[0]}"`,
            component: () => <LabeledExample value={labeledState} />,
            path: `${EXAMPLES_ROOT}/Labeled.tsx`,
        },
    ];

    return <PageExamples items={examples} />;
};
