<script lang="ts">
    import {
        LONG_TEXT,
        MAX_ROWS,
        MIN_ROWS,
        REVIEW_LIMIT,
    } from "@thewaver/ss-playground/App/Pages/TextAreaPage/TextAreaPage.const";

    import type { ExampleDefs } from "../../PageComponents/Examples/Examples.types";
    import PageExamples from "../../PageComponents/Examples/PageExamples.svelte";
    import AutoSizingExample from "./Examples/AutoSizing.svelte";
    import AutoSizingCappedExample from "./Examples/AutoSizingCapped.svelte";
    import DisabledExample from "./Examples/Disabled.svelte";
    import ErroredExample from "./Examples/Errored.svelte";
    import FixedHeightExample from "./Examples/FixedHeight.svelte";
    import LabeledExample from "./Examples/Labeled.svelte";
    import ReachableExample from "./Examples/Reachable.svelte";
    import ReadOnlyExample from "./Examples/ReadOnly.svelte";

    const EXAMPLES_ROOT = "/src/App/Pages/TextAreaPage/Examples";

    let fixedValue = $state("");
    let growingValue = $state("");
    let cappedValue = $state(LONG_TEXT);
    let readOnlyValue = $state("Generated by the server,\nacross two lines.");
    let disabledValue = $state("Cannot be edited");
    let reachableValue = $state("Cannot be edited either");
    let erroredValue = $state("Too short");
    let labeledValue = $state("");

    const examples: ExampleDefs[] = [
        {
            key: "fixedHeight",
            name: "Fixed height",
            readout: () => `length: ${fixedValue.length} — the painter sizes the box and it stays put`,
            component: fixedHeightExample,
            path: `${EXAMPLES_ROOT}/FixedHeight.svelte`,
        },
        {
            key: "autoSizing",
            name: "Auto-sizing",
            readout: () =>
                `length: ${growingValue.length} — grows from ${MIN_ROWS} rows with no ceiling, so it never scrolls`,
            component: autoSizingExample,
            path: `${EXAMPLES_ROOT}/AutoSizing.svelte`,
        },
        {
            key: "autoSizingCapped",
            name: "Auto-sizing, capped",
            readout: () => `length: ${cappedValue.length} — stops growing at ${MAX_ROWS} rows and scrolls`,
            component: autoSizingCappedExample,
            path: `${EXAMPLES_ROOT}/AutoSizingCapped.svelte`,
        },
        {
            key: "readOnly",
            name: "Read-only",
            readout: () => `length: ${readOnlyValue.length} — selectable and copyable, never editable`,
            component: readOnlyExample,
            path: `${EXAMPLES_ROOT}/ReadOnly.svelte`,
        },
        {
            key: "disabled",
            name: "Disabled",
            readout: () => `length: ${disabledValue.length}`,
            component: disabledExample,
            path: `${EXAMPLES_ROOT}/Disabled.svelte`,
        },
        {
            key: "reachable",
            name: "Disabled + reachable",
            readout: () => `length: ${reachableValue.length}`,
            component: reachableExample,
            path: `${EXAMPLES_ROOT}/Reachable.svelte`,
        },
        {
            key: "errored",
            name: "Error",
            readout: () => `length: ${erroredValue.length} — fewer than ${REVIEW_LIMIT} characters is an error`,
            component: erroredExample,
            path: `${EXAMPLES_ROOT}/Errored.svelte`,
        },
        {
            key: "label",
            name: "In a Label",
            readout: () => `length: ${labeledValue.length}`,
            component: labeledExample,
            path: `${EXAMPLES_ROOT}/Labeled.svelte`,
        },
    ];
</script>

{#snippet fixedHeightExample()}
    <FixedHeightExample bind:value={fixedValue} />
{/snippet}

{#snippet autoSizingExample()}
    <AutoSizingExample bind:value={growingValue} />
{/snippet}

{#snippet autoSizingCappedExample()}
    <AutoSizingCappedExample bind:value={cappedValue} />
{/snippet}

{#snippet readOnlyExample()}
    <ReadOnlyExample bind:value={readOnlyValue} />
{/snippet}

{#snippet disabledExample()}
    <DisabledExample bind:value={disabledValue} />
{/snippet}

{#snippet reachableExample()}
    <ReachableExample bind:value={reachableValue} />
{/snippet}

{#snippet erroredExample()}
    <ErroredExample bind:value={erroredValue} />
{/snippet}

{#snippet labeledExample()}
    <LabeledExample bind:value={labeledValue} />
{/snippet}

<PageExamples items={examples} minColumnWidth={400} />
